### ISSUE TITLE
Move to official salt-formulas

### ISSUE THREAD

**Issue by madflojo** [madflojo/salt-api-reactor-formula#2]
@basepi, Worthy of an official formula?

**Comment by basepi** [comment]
@whiteinge would you oblige?

**Comment by whiteinge** [comment]
Done! @madflojo you should have an invite to the Contributors team. Thanks for the addition.

https://github.com/saltstack-formulas/salt-api-reactor-formula

**Comment by madflojo** [comment]
Awesome thanks @basepi & @whiteinge excited for it to be official now ;)
